FROM node:23-alpine AS builder

WORKDIR /app

# Copy package.json and install dependencies
COPY package.json package-lock.json ./
RUN npm install

# Setup arguments (required at build time so need to be build arguments)
ARG SPP_API_URL
ENV REACT_APP_SPP_API_URL=$SPP_API_URL

# List arguments
RUN echo "Building with arguments:"
RUN echo "  REACT_APP_SPP_API_URL: $REACT_APP_SPP_API_URL"

# Copy and build the rest of the code
COPY . .
RUN npm run build

# Set environment to development and start the app
ENV PORT=8080
ENV CHOKIDAR_USEPOLLING=true
CMD ["npm", "start"]
