name: spp
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    image: spp-backend:dev
    container_name: spp-backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /tmp:/tmp
      - /var/run/docker.sock:/var/run/docker.sock  # For spawning containers in local mode
    environment:
      - NODE_ENV=development
      - EXEC_MODE=local
      - TRACE_TMP=/tmp/spp-usercode
      - USER_CODE_FILE_PREFIX=main
    networks:
      - spp-network
    depends_on:
      - code-runner-build

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    image: spp-frontend:dev
    container_name: spp-frontend
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app
    environment:
      - NODE_ENV=development
      - REACT_APP_API_URL=http://localhost:3000
    networks:
      - spp-network

  frontend-legacy:
    build:
      context: ./frontend-legacy
      dockerfile: Dockerfile.dev
    image: spp-frontend-legacy:dev
    container_name: spp-frontend-legacy
    ports:
      - "8000:8000"
    networks:
      - spp-network

  # Build code-runner image as part of compose
  code-runner-build:
    build:
      context: ./code-runner
      dockerfile: Dockerfile.dev
    image: spp-code-runner:dev
    deploy:
      replicas: 0 # Don't spin up an instance of the code-runner image
    command: echo "code-runner image built"

networks:
  spp-network:
    driver: bridge
  
  # Isolated network for user code execution
  spp-no-internet:
    driver: bridge
    internal: true