# ------------------------------------------------------------------------------------------------
# Build Stage
# ------------------------------------------------------------------------------------------------
FROM node:23-alpine AS builder

WORKDIR /app

# Copy package.json and install dependencies
COPY package*.json ./
RUN npm install

# Setup arguments
ARG ALLOWED_ORIGIN_REGEX
ENV ALLOWED_ORIGIN_REGEX=$ALLOWED_ORIGIN_REGEX
RUN echo "Building with allowed origin regex: $ALLOWED_ORIGIN_REGEX"

ARG EXEC_MODE
ENV EXEC_MODE=$EXEC_MODE
RUN echo "Building with exec mode: $EXEC_MODE"

# Copy the rest of the codebase and build the app
COPY . .
RUN npm run build

# ------------------------------------------------------------------------------------------------
# Production Stage
# ------------------------------------------------------------------------------------------------
FROM node:23-alpine

WORKDIR /app

# Copy package.json and install dependencies
COPY package*.json ./
RUN npm install --only=production

# Copy the build output
COPY --from=builder /app/dist ./dist

EXPOSE 3000
CMD ["node", "dist/index.js"]
