version = 0.1

[default]
[default.build.parameters]
cached = true
parallel = true

[default.deploy.parameters]
stack_name = "spp-lambda-dev"
s3_prefix = "spp-lambda"
region = "us-west-2"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=dev"
image_repositories = []

[dev]
[dev.deploy.parameters]
stack_name = "spp-lambda-dev"
s3_prefix = "spp-lambda-dev"
region = "us-west-2"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=dev"

[test]
[test.deploy.parameters]
stack_name = "spp-lambda-test"
s3_prefix = "spp-lambda-test"
region = "us-west-2"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=test"

[prod]
[prod.deploy.parameters]
stack_name = "spp-lambda-prod"
s3_prefix = "spp-lambda-prod"
region = "us-west-2"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=prod"
