#!/usr/bin/env bash
# Deterministic port + DB-name allocator for a See++ worktree.
# Usage: ./scripts/worktree-ports.sh <worktree-slug>
#
# Hashes the slug into a 0..899 offset, then adds it to fixed bases so ports
# across worktrees don't collide and stay reproducible across re-runs.
#
#   BACKEND_PORT  = 3100 + offset
#   FRONTEND_PORT = 4100 + offset
#   DB_PORT       = 5100 + offset
#   DB_NAME       = seepp_<slug-with-underscores>
#
# The main clone (no .env / no slug) uses docker-compose.yml's
# defaults: 3000 / 4000 / 5432.
#
# Safe-merge: if `.env` already exists with other values (OAuth creds,
# SESSION_SECRET, etc.), this script preserves them. Only the worktree
# override lines are replaced.
set -euo pipefail

if [ $# -ne 1 ]; then
  echo "usage: $0 <worktree-slug>" >&2
  exit 1
fi

slug="$1"

if ! [[ "$slug" =~ ^[a-z0-9-]+$ ]]; then
  echo "error: slug must be lowercase kebab-case (got: $slug)" >&2
  exit 1
fi

hex=$(printf '%s' "$slug" | shasum -a 256 | cut -c1-4)
offset=$((16#$hex % 900))

BACKEND_PORT=$((3100 + offset))
FRONTEND_PORT=$((4100 + offset))
DB_PORT=$((5100 + offset))
DB_NAME="seepp_${slug//-/_}"

envfile=".env"
managed_begin="# --- worktree-ports.sh (managed block — do not edit by hand) ---"
managed_end="# --- /worktree-ports.sh ---"

managed_block=$(cat <<EOF
$managed_begin
# Regenerate by re-running ./scripts/worktree-ports.sh $slug.
WORKTREE_SLUG=$slug
BACKEND_PORT=$BACKEND_PORT
FRONTEND_PORT=$FRONTEND_PORT
DB_PORT=$DB_PORT
DB_NAME=$DB_NAME
$managed_end
EOF
)

if [ -f "$envfile" ]; then
  # Replace the managed block in-place if present; else append.
  if grep -qF "$managed_begin" "$envfile"; then
    # Write everything outside the managed block, then the new block.
    tmp=$(mktemp)
    awk -v begin="$managed_begin" -v end="$managed_end" '
      $0 == begin { skip = 1; next }
      $0 == end   { skip = 0; next }
      !skip
    ' "$envfile" > "$tmp"
    printf '\n%s\n' "$managed_block" >> "$tmp"
    mv "$tmp" "$envfile"
  else
    printf '\n%s\n' "$managed_block" >> "$envfile"
  fi
else
  # Fresh .env — write just the managed block, with a header pointing at
  # the example for other settings.
  cat > "$envfile" <<EOF
# Generated by scripts/worktree-ports.sh. Add other settings (auth, etc.)
# by copying from .env.example. Gitignored.
$managed_block
EOF
fi

echo "updated $envfile for worktree \"$slug\":"
echo "  BACKEND_PORT=$BACKEND_PORT"
echo "  FRONTEND_PORT=$FRONTEND_PORT"
echo "  DB_PORT=$DB_PORT"
echo "  DB_NAME=$DB_NAME"
