#!/usr/bin/env bash
# Deterministic port + DB-name allocator for a See++ worktree.
# Usage: ./scripts/worktree-ports.sh <worktree-slug>
#
# Hashes the slug into a 0..899 offset, then adds it to fixed bases so ports
# across worktrees don't collide and stay reproducible across re-runs.
#
#   BACKEND_PORT  = 3100 + offset
#   FRONTEND_PORT = 4100 + offset
#   DB_PORT       = 5100 + offset
#   DB_NAME       = seepp_<slug-with-underscores>
#
# The main clone (no .env.local / no slug) uses docker-compose.v2.yml's
# defaults: 3000 / 4000 / 5432.
set -euo pipefail

if [ $# -ne 1 ]; then
  echo "usage: $0 <worktree-slug>" >&2
  exit 1
fi

slug="$1"

if ! [[ "$slug" =~ ^[a-z0-9-]+$ ]]; then
  echo "error: slug must be lowercase kebab-case (got: $slug)" >&2
  exit 1
fi

hex=$(printf '%s' "$slug" | shasum -a 256 | cut -c1-4)
offset=$((16#$hex % 900))

BACKEND_PORT=$((3100 + offset))
FRONTEND_PORT=$((4100 + offset))
DB_PORT=$((5100 + offset))
DB_NAME="seepp_${slug//-/_}"

cat > .env.local <<EOF
# Generated by scripts/worktree-ports.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ).
# Deterministic from slug "$slug"; regenerate by re-running the script.
# Used by docker-compose.yml and localdev.sh. Gitignored.
WORKTREE_SLUG=$slug
BACKEND_PORT=$BACKEND_PORT
FRONTEND_PORT=$FRONTEND_PORT
DB_PORT=$DB_PORT
DB_NAME=$DB_NAME
EOF

echo "wrote .env.local for worktree \"$slug\":"
echo "  BACKEND_PORT=$BACKEND_PORT"
echo "  FRONTEND_PORT=$FRONTEND_PORT"
echo "  DB_PORT=$DB_PORT"
echo "  DB_NAME=$DB_NAME"
